module.exports = Object.freeze({
  MODAL_BODY_TYPES: {
    USER_DETAIL: "USER_DETAIL",
    ROLE_ADD_NEW: "ROLE_ADD_NEW",
    LEAD_ADD_NEW: "LEAD_ADD_NEW",
    CONFIRMATION: "CONFIRMATION",
    DEFAULT: "",
  },

  RIGHT_DRAWER_TYPES: {
    ROLE_ADD_NEW: "ROLE_ADD_NEW",
    NOTIFICATION: "NOTIFICATION",
    CALENDAR_EVENTS: "CALENDAR_EVENTS",
    USER_DRAWER: "USER_DRAWER",
    UPDATE_ROLE_DRAWER: "UPDATE_ROLE_DRAWER",
    // UPDATE_USER_DRAWER: "UPDATE_USER_DRAWER",
    VIEW_RIGHT_SIDE_DRAWER: "VIEW_RIGHT_SIDE_DRAWER",
    ADD_NEW_USER: "ADD_NEW_USER",
    UPDATE_USER: "UPDATE_USER",
    VIEW_USER: "VIEW_USER",
    ROUTE_ADD_NEW: "ROUTE_ADD_NEW",
    VIEW_ROUTE_DATA: "VIEW_ROUTE_DATA",
    ROUTE_UPDATE_NEW: "ROUTE_UPDATE_NEW",
    ACCESS_ADD_NEW: "ACCESS_ADD_NEW",
    VIEW_ACCESS_DATA: "VIEW_ACCESS_DATA",
    UPDATE_ACCESS_DATA: "UPDATE_ACCESS_DATA",
  },

  CONFIRMATION_MODAL_CLOSE_TYPES: {
    LEAD_DELETE: "LEAD_DELETE",
    ROLE_DELETE: "",
    UPDATE_ROLE: "UPDATE_ROLE",
    USER_DELETE: "USER_DELETE",
    UPDATE_USER: "UPDATE_USER",
    ROUTING_DELETE: "ROUTING_DELETE"
  },
  // CONFIRMATION_MODAL_CLOSE_TYPES: {
  //   LEAD_DELETE: "LEAD_DELETE",
  // },
});
